import type { Metadata } from 'next'
import { A, LegalPage, Section, Src } from '@/components/marketing/LegalPage'
import { ALIAS_FOUND_ON, ALIAS_HEADER, ALIAS_HOST, ALIAS_RULE } from '@/config/aliasNoindex'
import { BLOG_POSTS, formatPostDate, postMetadata } from '@/config/blog'

const post = BLOG_POSTS.find((p) => p.slug === 'cloudflare-pages-dev-duplicate')!

export const metadata: Metadata = postMetadata(post)

/** A `_headers` rule, shown the way the file writes it. */
function Rule({ pattern, header }: { pattern: string; header: string }) {
  return (
    <div className="mt-4 overflow-x-auto rounded-2xl border border-foreground/10 bg-foreground/[0.03] px-4 py-3">
      <p className="text-xs leading-relaxed">
        <code>{pattern}</code>
        <br />
        <code>&nbsp;&nbsp;{header}</code>
      </p>
    </div>
  )
}

export default function PagesDevDuplicatePost() {
  return (
    <LegalPage
      title={post.title}
      subtitle={formatPostDate(post.date)}
      back={{ href: '/blog', label: 'All posts' }}
    >
      <Section title="The host you stopped thinking about">
        <p>
          Cloudflare Pages gives every project a <code>pages.dev</code> subdomain. You point a
          custom domain at it, you tell people the custom domain, and the other one carries on
          serving. That is the whole bug.
        </p>
        <p>
          On {ALIAS_FOUND_ON} we checked ours from outside. <code>{ALIAS_HOST}</code> returned 200
          with the current production build on it, every path, and no <code>X-Robots-Tag</code> of
          any kind. The site was crawlable on two hostnames, and the copy did not know it was the
          copy.
        </p>
      </Section>

      <Section title="The documentation covers the other host">
        <p>
          Cloudflare does add the header, and says so plainly:{' '}
          <em>
            every preview deployment generated by Cloudflare Pages includes the{' '}
            <code>X-Robots-Tag: noindex</code> HTTP response header
          </em>
          .
        </p>
        <p>
          A preview deployment is the per-commit one, at <code>&lt;hash&gt;.{ALIAS_HOST}</code>. The
          production alias is a different address, it is the one printed in your dashboard, and that
          page does not mention it either way. So the sentence that sounds like reassurance is about
          a host you were not worried about. We read it as covering both for five weeks.
        </p>
      </Section>

      <Section title="The canonical tag was already right, and did not help">
        <p>
          Every page on the site carries a canonical pointing at <code>playpip.io</code>, including
          the pages served on the alias. It was correct the entire time.
        </p>
        <p>
          It is also not an instruction. Google&rsquo;s own documentation calls{' '}
          <code>rel=&quot;canonical&quot;</code>{' '}
          <em>a strong signal that the specified URL should become canonical</em>, and{' '}
          <A href="https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls">
            the page it appears on
          </A>{' '}
          is upfront that Google decides which version to show. A signal is weighed. A header is
          obeyed.
        </p>
        <p>
          On a domain five weeks old with almost no links pointing at it, that difference is the
          difference between a weak set of ranking signals and two weaker ones. Nobody arrives at
          your site by ranking twice.
        </p>
      </Section>

      <Section title="Why it is not a redirect">
        <p>
          The obvious fix is a 301 from the alias to the real domain. On Pages a redirect with logic
          in it means a Function, and the only Function that sees a request for a static file is{' '}
          <code>functions/_middleware.ts</code> at the root.{' '}
          <A href="https://developers.cloudflare.com/pages/functions/middleware/">
            Cloudflare&rsquo;s docs
          </A>{' '}
          are specific about what that costs:{' '}
          <em>
            if you want to run a middleware on your entire application, including in front of static
            files, create a <code>functions/_middleware.js</code> file
          </em>
          .
        </p>
        <p>
          Entire application includes the host you actually care about. You would be putting a
          Worker invocation in front of every chunk, image and font on <code>playpip.io</code> in
          order to tidy up a hostname nobody visits. You can check the hostname and return early
          inside the middleware, but by then the invocation has happened: that is the part you were
          trying not to pay for.
        </p>
        <p>
          <Src path="public/_headers" /> is read by the CDN, applies per host, and costs nothing at
          runtime.
        </p>
      </Section>

      <Section title="The rule">
        <Rule pattern={ALIAS_RULE} header={ALIAS_HEADER} />
        <p>
          A <code>_headers</code> pattern written with a scheme and a host matches that host only.{' '}
          <code>playpip.io</code> is untouched, and preview deployments are a third host again and
          keep the <code>noindex</code> Cloudflare gives them, which is worth preserving: a
          preview&rsquo;s permanent address is how you audit a build from outside after something
          has gone wrong on it.
        </p>
      </Section>

      <Section title="The same file, one edit later">
        <p>Now delete the host from that pattern.</p>
        <Rule pattern="/*" header={ALIAS_HEADER} />
        <p>
          The site is gone from search. Every path, on the real domain. The deploy is green, the
          suite passes, the site opens perfectly for every human being who visits, and there is
          nothing in the repository a linter or a type checker could object to, because{' '}
          <code>_headers</code> is a text file the CDN interprets after you have shipped it. It is
          the one file here that can do that, and nothing was reading it.
        </p>
        <p>
          So something does now. <Src path="tests/headers.test.ts" /> parses the file the way Pages
          does, an unindented line being a pattern and the indented lines under it being its
          headers, and holds one invariant: no rule that sets <code>noindex</code> may match the
          site itself. It collects the offending rules and compares the list to empty, rather than
          asserting rule by rule, so it still runs an assertion when the file contains no{' '}
          <code>noindex</code> at all. A test that passes by finding nothing to check is the other
          way to be green and wrong.
        </p>
        <p>
          Then break the file three ways and watch, because a test written against a file that
          already passes has proved nothing about itself. Dropping the host fails two tests.
          Deleting the whole rule fails one. Taking the <code>noindex</code> line out and leaving
          the pattern behind fails two others, and the invariant test goes green, which is the right
          answer: there is no <code>noindex</code> left anywhere to reach anything. It is still
          executing a comparison at that point rather than skipping an empty loop, and that is the
          only reason its green is worth reading.
        </p>
      </Section>

      <Section title="What we cannot tell you">
        <p>
          What the duplicate cost us, because we never measured it. The alias was never verified as
          a Search Console property of ours, so there is no report to go back and open, and we fixed
          it the morning we found it rather than leaving it up to find out. It may have cost nothing
          at all. It was also five weeks of a young domain&rsquo;s crawling spent twice on the same
          pages, which is the sort of thing worth fixing without a number attached.
        </p>
      </Section>

      <Section title="Thirty seconds">
        <p>
          If you are on Pages, run <code>curl -I https://&lt;your-project&gt;.pages.dev/</code> and
          look for <code>x-robots-tag</code> in the output. If it is not there, you are the second
          website about your own product, and you are competing with yourself for the handful of
          people who were going to find either one.
        </p>
      </Section>
    </LegalPage>
  )
}
