// The written guides' table of contents. Each guide is a static page under
// src/app/learn/<slug>/ — this registry drives the index on /learn, the
// sitemap, the Markdown mirrors, and per-page metadata, so a new guide is one
// folder plus one entry here.
//
// These are prose pages, and a different thing from the interactive tour that
// /learn itself renders. The tour stays exactly as it is: free, unmetered, one
// URL. See ../components/learn/Tutorial.tsx.

/**
 * A piece of guide artwork. Every guide's art is generated by the marketing
 * repo's capture harness from the product's own card faces, so a chart that
 * gets reposted carries Pip's cards rather than a lookalike's.
 *
 * Dimensions are the file's real ones and are required: the browser needs them
 * to reserve the space before the image loads, and an image that arrives late
 * and shoves the prose down is worse than no image.
 */
export interface GuideArt {
  /** Path under /public. */
  src: string
  /** Describes what the picture shows, for readers who can't see it. */
  alt: string
  width: number
  height: number
}

export interface LearnGuide {
  /** URL segment — must match the guide's folder under src/app/learn/. */
  slug: string
  /** The page's H1 and its heading on the index. The query, near-verbatim. */
  title: string
  /** The <title> tag — carries the qualifier the H1 leaves off. */
  metaTitle: string
  /** Meta description, and the blurb under the heading on the index. */
  description: string
  /** ISO date, e.g. '2026-08-05'. Drives the sitemap's lastModified. */
  date: string
  /**
   * Sibling guides linked at the foot of the page. Slugs that aren't in this
   * registry yet are dropped rather than rendered, so a guide can name the
   * siblings it wants before they're written without shipping a dead link.
   */
  related: string[]
  /**
   * The banner at the top of the page, which doubles as the guide's OG card —
   * one file, so a shared link previews as the guide instead of as the site.
   * Wants 1200x630 or a multiple of it. Optional: a guide without one falls
   * back to the site-wide card from app/opengraph-image.tsx.
   */
  hero?: GuideArt
  /**
   * An in-body chart. This is the asset that earns backlinks, so it is separate
   * from the hero rather than sharing a field: they have different jobs, only
   * some guides have both, and the page decides where the chart sits.
   */
  chart?: GuideArt
}

/** Absolute URL for an image, which is what OG and Twitter cards require. */
export function guideArtUrl(art: GuideArt): string {
  return `https://playpip.io${art.src}`
}

/**
 * Ranked, not dated — the index renders this order as-is. The ranking is by
 * query intent (see the marketing plan), and it is explicitly not settled:
 * once Search Console has a few months of real impressions, it should be
 * reordered from that rather than from reasoning.
 */
export const LEARN_GUIDES: LearnGuide[] = [
  {
    slug: 'hand-rankings',
    title: 'Poker hand rankings',
    metaTitle: 'Poker hand rankings: what beats what in Texas Hold’em',
    description:
      'All ten poker hands in order, strongest to weakest, with how ties are settled and how often each one actually turns up. No signup, and you can practise straight away.',
    date: '2026-08-05',
    related: ['how-to-play-texas-holdem', 'starting-hands', 'position'],
    hero: {
      src: '/learn/hand-rankings-hero.png',
      alt: 'A royal flush spread across a table: ace, king, queen, jack and ten of spades.',
      width: 2400,
      height: 1260,
    },
    chart: {
      src: '/learn/hand-rankings-chart.png',
      alt: 'All ten poker hands in order from royal flush down to high card, each shown as five playing cards.',
      width: 2400,
      height: 3464,
    },
  },
]

export function guideBySlug(slug: string): LearnGuide | undefined {
  return LEARN_GUIDES.find((guide) => guide.slug === slug)
}

/**
 * The siblings a guide links to, filtered to the ones that actually exist.
 * Order follows the guide's own `related` list, not the registry's.
 */
export function relatedGuides(slug: string): LearnGuide[] {
  const guide = guideBySlug(slug)
  if (!guide) return []
  return guide.related
    .map(guideBySlug)
    .filter((sibling): sibling is LearnGuide => sibling !== undefined)
}
