// The written guides' table of contents. Each guide is a static page under
// src/app/learn/<slug>/ — this registry drives the index on /learn, the
// sitemap, the Markdown mirrors, and per-page metadata, so a new guide is one
// folder plus one entry here.
//
// These are prose pages, and a different thing from the interactive tour that
// /learn itself renders. The tour stays exactly as it is: free, unmetered, one
// URL. See ../components/learn/Tutorial.tsx.

/**
 * A piece of guide artwork. Every guide's art is generated by the marketing
 * repo's capture harness from the product's own card faces, so a chart that
 * gets reposted carries Pip's cards rather than a lookalike's.
 *
 * Dimensions are the file's real ones and are required: the browser needs them
 * to reserve the space before the image loads, and an image that arrives late
 * and shoves the prose down is worse than no image.
 */
export interface GuideArt {
  /** Path under /public. */
  src: string
  /** Describes what the picture shows, for readers who can't see it. */
  alt: string
  width: number
  height: number
}

export interface LearnGuide {
  /** URL segment — must match the guide's folder under src/app/learn/. */
  slug: string
  /** The page's H1 and its heading on the index. The query, near-verbatim. */
  title: string
  /** The <title> tag — carries the qualifier the H1 leaves off. */
  metaTitle: string
  /** Meta description, and the blurb under the heading on the index. */
  description: string
  /** ISO date, e.g. '2026-08-05'. Drives the sitemap's lastModified. */
  date: string
  /**
   * Sibling guides linked at the foot of the page. Slugs that aren't in this
   * registry yet are dropped rather than rendered, so a guide can name the
   * siblings it wants before they're written without shipping a dead link.
   */
  related: string[]
  /**
   * The banner at the top of the page, which doubles as the guide's OG card —
   * one file, so a shared link previews as the guide instead of as the site.
   * Wants 1200x630 or a multiple of it. Optional: a guide without one falls
   * back to the site-wide card from app/opengraph-image.tsx.
   */
  hero?: GuideArt
  /**
   * An in-body chart. This is the asset that earns backlinks, so it is separate
   * from the hero rather than sharing a field: they have different jobs, only
   * some guides have both, and the page decides where the chart sits.
   */
  chart?: GuideArt
}

/** Absolute URL for an image, which is what OG and Twitter cards require. */
export function guideArtUrl(art: GuideArt): string {
  return `https://playpip.io${art.src}`
}

/**
 * The `images` fragment for a guide's Open Graph and Twitter cards, spread into
 * both by the page. Without it a shared guide link previews as the site's
 * generic card, so what arrives in the chat looks like Pip in general rather
 * than the page somebody meant to send.
 *
 * It lives here rather than in each page because it is the same eight lines
 * every time, and the failure mode is silent: a guide that forgets it still
 * builds, still ships, and still previews as something plausible.
 */
export function guideCard(guide: LearnGuide) {
  if (!guide.hero) return {}
  const { hero } = guide
  return {
    images: [{ url: guideArtUrl(hero), width: hero.width, height: hero.height, alt: hero.alt }],
  }
}

/**
 * Ranked, not dated — the index renders this order as-is. The ranking is by
 * query intent (see the marketing plan), and it is explicitly not settled:
 * once Search Console has a few months of real impressions, it should be
 * reordered from that rather than from reasoning.
 */
export const LEARN_GUIDES: LearnGuide[] = [
  {
    slug: 'hand-rankings',
    title: 'Poker hand rankings',
    metaTitle: 'Poker hand rankings: what beats what in Texas Hold’em',
    description:
      'All ten poker hands in order, strongest to weakest, with how ties are settled and how often each one actually turns up. No signup, and you can practise straight away.',
    date: '2026-08-05',
    related: ['how-to-play-texas-holdem', 'starting-hands', 'position'],
    hero: {
      src: '/learn/hand-rankings-hero.png',
      alt: 'A royal flush spread across a table: ace, king, queen, jack and ten of spades.',
      width: 2400,
      height: 1260,
    },
    chart: {
      src: '/learn/hand-rankings-chart.png',
      alt: 'All ten poker hands in order from royal flush down to high card, each shown as five playing cards.',
      width: 2400,
      height: 3464,
    },
  },
  {
    slug: 'how-to-play-texas-holdem',
    title: 'How to play Texas Hold’em',
    metaTitle: 'How to play Texas Hold’em: the rules, in the order they happen',
    description:
      'The rules of Texas Hold’em in the order you meet them at a table: the blinds, the four betting rounds, what you can do on your turn, and a full hand played out. No signup, and you can practise straight away.',
    date: '2026-08-09',
    related: ['hand-rankings', 'starting-hands', 'position'],
    hero: {
      src: '/learn/how-to-play-texas-holdem-hero.png',
      alt: 'Five community cards face up in a row: the king of diamonds, the eight of spades, the three of hearts, the five of clubs and the queen of hearts.',
      width: 2400,
      height: 1260,
    },
  },
  {
    slug: 'starting-hands',
    title: 'Which starting hands to play',
    metaTitle: 'Poker starting hands: a chart that tells you when, not just what',
    description:
      'All 169 starting hands in one chart, sorted by the earliest position you should open them from. Plus how often each one arrives and what suitedness is actually worth. No signup, and you can practise straight away.',
    date: '2026-08-09',
    related: ['hand-rankings', 'how-to-play-texas-holdem', 'position'],
    hero: {
      src: '/learn/starting-hands-hero.png',
      alt: 'Two hole cards face up: the ace of spades and the king of spades.',
      width: 2400,
      height: 1260,
    },
    // No `chart` on purpose, and the file exists anyway:
    // /learn/starting-hands-chart.png is the whole 13x13 grid as one picture.
    // The chart on this page is interactive, so a static copy of it in the body
    // would be the same chart twice and the worse one of the two. The image is
    // built for somewhere else: a forum post, a reply, somebody else's article.
  },
]

export function guideBySlug(slug: string): LearnGuide | undefined {
  return LEARN_GUIDES.find((guide) => guide.slug === slug)
}

/**
 * The siblings a guide links to, filtered to the ones that actually exist.
 * Order follows the guide's own `related` list, not the registry's.
 */
export function relatedGuides(slug: string): LearnGuide[] {
  const guide = guideBySlug(slug)
  if (!guide) return []
  return guide.related
    .map(guideBySlug)
    .filter((sibling): sibling is LearnGuide => sibling !== undefined)
}
