// The written guides' table of contents. Each guide is a static page under
// src/app/learn/<slug>/ — this registry drives the index on /learn, the
// sitemap, the Markdown mirrors, and per-page metadata, so a new guide is one
// folder plus one entry here.
//
// These are prose pages, and a different thing from the interactive tour that
// /learn itself renders. The tour stays exactly as it is: free, unmetered, one
// URL. See ../components/learn/Tutorial.tsx.

import type { SocialImage } from './site'

/**
 * A piece of guide artwork. Every guide's art is generated by the marketing
 * repo's capture harness from the product's own card faces, so a chart that
 * gets reposted carries Pip's cards rather than a lookalike's.
 *
 * Dimensions are the file's real ones and are required: the browser needs them
 * to reserve the space before the image loads, and an image that arrives late
 * and shoves the prose down is worse than no image.
 */
export interface GuideArt {
  /** Path under /public. */
  src: string
  /** Describes what the picture shows, for readers who can't see it. */
  alt: string
  width: number
  height: number
}

export interface LearnGuide {
  /** URL segment — must match the guide's folder under src/app/learn/. */
  slug: string
  /**
   * What sort of page this is, which only the /learn index cares about.
   *
   * A `guide` is a pillar: one broad subject, eight sections, artwork. An
   * `answer` is one narrow question, one number and where the number came from,
   * and it exists because the pillars sit at search positions 73 to 97 while
   * the narrow queries are the ones a young domain might actually rank for
   * (marketing#83). They share this registry, and therefore the sitemap, the
   * Markdown mirrors and the page chrome, because the only thing that differs
   * is the writing. Absent means `guide`.
   */
  kind?: 'guide' | 'answer'
  /** The page's H1 and its heading on the index. The query, near-verbatim. */
  title: string
  /** The <title> tag — carries the qualifier the H1 leaves off. */
  metaTitle: string
  /** Meta description, and the blurb under the heading on the index. */
  description: string
  /** ISO date, e.g. '2026-08-05'. Drives the sitemap's lastModified. */
  date: string
  /**
   * Sibling guides linked at the foot of the page. Slugs that aren't in this
   * registry yet are dropped rather than rendered, so a guide can name the
   * siblings it wants before they're written without shipping a dead link.
   */
  related: string[]
  /**
   * The banner at the top of the page, which doubles as the guide's OG card —
   * one file, so a shared link previews as the guide instead of as the site.
   * Wants 1200x630 or a multiple of it. Optional: a guide without one falls
   * back to the site-wide card from app/opengraph-image.tsx.
   */
  hero?: GuideArt
  /**
   * An in-body chart. This is the asset that earns backlinks, so it is separate
   * from the hero rather than sharing a field: they have different jobs, only
   * some guides have both, and the page decides where the chart sits.
   */
  chart?: GuideArt
  /**
   * A chart we explicitly offer for reposting, rendered as an offer and a
   * copy-paste credit snippet by components/learn/ReuseChart.tsx.
   *
   * Separate from `chart` because the jobs differ: `chart` is the picture that
   * illustrates this page, this is the picture that goes on somebody else's.
   * A guide can have one, the other, both or neither. Registering it here is
   * also what puts the file under the size check in tests/learn.test.ts: an
   * offered image that nothing on the site renders is otherwise the one asset
   * no part of the build ever looks at.
   */
  reusable?: GuideArt
}

/** Absolute URL for an image, which is what OG and Twitter cards require. */
export function guideArtUrl(art: GuideArt): string {
  return `https://playpip.io${art.src}`
}

/**
 * A guide's hero as a share card, or undefined for Pip's own.
 *
 * Here rather than in each guide page so that giving a guide a hero is one
 * entry in the registry below and nothing else. Written out per page, it was
 * three copies of the same ternary and a fourth guide would have needed a
 * fourth — and `undefined` rather than `{}` so a guide with no art falls back
 * to the site card instead of shipping a large-image card with nothing in it.
 */
export function guideCardImage(guide: LearnGuide): SocialImage | undefined {
  if (!guide.hero) return undefined
  return {
    url: guideArtUrl(guide.hero),
    width: guide.hero.width,
    height: guide.hero.height,
    alt: guide.hero.alt,
  }
}

/**
 * Ranked, not dated — the index renders this order as-is. The ranking is by
 * query intent (see the marketing plan), and it is explicitly not settled:
 * once Search Console has a few months of real impressions, it should be
 * reordered from that rather than from reasoning.
 */
export const LEARN_GUIDES: LearnGuide[] = [
  {
    slug: 'hand-rankings',
    title: 'Poker hand rankings',
    metaTitle: 'Poker hand rankings: what beats what in Texas Hold’em',
    description:
      'All ten poker hands in order, strongest to weakest, with how ties are settled and how often each one actually turns up. No signup, and you can practise straight away.',
    date: '2026-08-05',
    related: ['how-to-play-texas-holdem', 'starting-hands', 'position'],
    hero: {
      src: '/learn/hand-rankings-hero.png',
      alt: 'A royal flush spread across a table: ace, king, queen, jack and ten of spades.',
      width: 2400,
      height: 1260,
    },
    chart: {
      src: '/learn/hand-rankings-chart.png',
      alt: 'All ten poker hands in order from royal flush down to high card, each shown as five playing cards.',
      width: 2400,
      height: 3464,
    },
  },
  {
    slug: 'how-to-play-texas-holdem',
    title: 'How to play Texas Hold’em',
    metaTitle: 'How to play Texas Hold’em: the rules, in the order they happen',
    description:
      'The rules of Texas Hold’em in the order you meet them at a table: the blinds, the four betting rounds, what you can do on your turn, and a full hand played out. No signup, and you can practise straight away.',
    date: '2026-08-09',
    related: ['hand-rankings', 'starting-hands', 'position'],
    hero: {
      src: '/learn/how-to-play-texas-holdem-hero.png',
      alt: 'Five community cards face up in a row: the king of diamonds, the eight of spades, the three of hearts, the five of clubs and the queen of hearts.',
      width: 2400,
      height: 1260,
    },
  },
  {
    slug: 'starting-hands',
    title: 'Which starting hands to play',
    metaTitle: 'Poker starting hands: a chart that tells you when, not just what',
    description:
      'All 169 starting hands in one chart, sorted by the earliest position you should open them from. Plus how often each one arrives and what suitedness is actually worth. No signup, and you can practise straight away.',
    date: '2026-08-09',
    related: [
      'hand-rankings',
      'how-to-play-texas-holdem',
      'position',
      'how-often-do-you-flop-a-set',
    ],
    hero: {
      src: '/learn/starting-hands-hero.png',
      alt: 'Two hole cards face up: the ace of spades and the king of spades.',
      width: 2400,
      height: 1260,
    },
    // No `chart` on purpose. The chart on this page is interactive, so a static
    // copy of it in the body would be the same chart twice and the worse one of
    // the two. The picture is built for somewhere else: a forum post, a reply,
    // somebody else's article. That is what `reusable` is for.
    reusable: {
      src: '/learn/starting-hands-chart.png',
      alt: 'Texas Hold’em starting hand chart: all 169 starting hands in a 13x13 grid, each marked with the earliest position it is worth opening from.',
      width: 2400,
      height: 3262,
    },
  },
  {
    slug: 'pot-odds',
    title: 'How to calculate pot odds',
    metaTitle: 'Pot odds: how to work out whether a call makes money',
    description:
      'Pot odds in one formula, with the price every common bet size sets, how many outs each draw really has, and the mistake that makes most pot-odds advice wrong. No signup, and you can practise straight away.',
    date: '2026-08-10',
    related: ['hand-rankings', 'starting-hands', 'position', 'bet-sizing'],
    hero: {
      src: '/learn/pot-odds-hero.png',
      alt: 'Two hole cards, the eight and seven of spades, beside a flop of the nine of spades, the four of spades and the two of hearts: four spades, so a flush draw.',
      width: 2400,
      height: 1260,
    },
  },
  {
    slug: 'position',
    title: 'Position in poker',
    metaTitle: 'Position in poker: why the button is the best seat at the table',
    description:
      'What position means, the six seats in the order they act, and why the same two cards are a fold in one seat and a raise in another. With the numbers behind it. No signup, and you can practise straight away.',
    date: '2026-08-10',
    related: ['starting-hands', 'how-to-play-texas-holdem', 'pot-odds'],
    hero: {
      src: '/learn/position-hero.png',
      alt: 'Two hole cards, the jack and nine of spades, with the dealer button beside them.',
      width: 2400,
      height: 1260,
    },
  },
  {
    slug: 'bet-sizing',
    title: 'How much to bet',
    metaTitle: 'Poker bet sizing: how much to bet, and what each size costs you',
    description:
      'Every bet sets two prices, one for the other player and one for you. The four sizes worth using, what each one charges a draw, and why a pot-sized bluff has to work half the time. No signup, and you can practise straight away.',
    date: '2026-08-10',
    related: ['pot-odds', 'position', 'starting-hands'],
    hero: {
      src: '/learn/bet-sizing-hero.png',
      alt: 'Three stacks of chips of increasing height, labelled third pot, half pot and pot, marked with how often a bluff of that size has to work to break even: 25%, 33.3% and 50%.',
      width: 2400,
      height: 1260,
    },
  },
  {
    slug: 'how-often-do-you-flop-a-set',
    kind: 'answer',
    title: 'How often do you flop a set?',
    metaTitle: 'How often do you flop a set with a pocket pair?',
    description:
      'About 11.8% of the time, or one flop in 8.5. All 19,600 flops a pocket pair can meet, graded, including the 48 that hand you a full house without a card of your rank in them.',
    date: '2026-08-21',
    related: ['pot-odds', 'starting-hands', 'hand-rankings'],
    // No hero and no chart, on purpose. The artwork is the expensive half of a
    // pillar guide and the whole argument for answer pages is that they cost
    // nearly nothing to write. If the format works, sixty of them should not
    // need sixty renders.
  },
]

/** Pillar guides: one broad subject each, in the order the index lists them. */
export const PILLAR_GUIDES: LearnGuide[] = LEARN_GUIDES.filter(
  (guide) => (guide.kind ?? 'guide') === 'guide',
)

/** Answer pages: one narrow question each. */
export const ANSWER_PAGES: LearnGuide[] = LEARN_GUIDES.filter((guide) => guide.kind === 'answer')

export function guideBySlug(slug: string): LearnGuide | undefined {
  return LEARN_GUIDES.find((guide) => guide.slug === slug)
}

/**
 * The siblings a guide links to, filtered to the ones that actually exist.
 * Order follows the guide's own `related` list, not the registry's.
 */
export function relatedGuides(slug: string): LearnGuide[] {
  const guide = guideBySlug(slug)
  if (!guide) return []
  return guide.related
    .map(guideBySlug)
    .filter((sibling): sibling is LearnGuide => sibling !== undefined)
}
